#after pods are in running stage I used minikube ip like http://minikubeip/30001
#if you are using k8 cluster can use node ip 


apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4499
      nodePort: 30001

